export const images = {
    sitelogo: require("../assets/images/logo/mylogo.png"),
    aboutme: require("../assets/images/content/aboutme.png"),
    certifications: require("../assets/images/content/certificates.jpg"),
    cloudeservices: require("../assets/images/content/cloudservices.png"),
    datasceince: require("../assets/images/content/dataanalysis.png"),
    designer: require("../assets/images/content/desin.png"),
    contactme: require("../assets/images/content/contactme2.jpg"),
    experience: require("../assets/images/content/experience.jpg"),
    machinelearning: require("../assets/images/content/machinelearning.png"),
    mobiledev: require("../assets/images/content/mobiledev.png"),
    webservices: require("../assets/images/content/webdev.png"),
    contact: require("../assets/images/content/contactme.png"),
    footerImage: require("../assets/images/content/wave.png"),
    wefavicon: require("../assets/images/logo/logotag.png"),

    // Projects
    projectFIC: require("../assets/images/Projects/ficwebsite.png"),
    proDashboad: require("../assets/images/Projects/admin.png"),
    proCounter: require("../assets/images/Projects/counter.png"),
    proShopping: require("../assets/images/Projects/shoppingcart.png"),
    proTodoList: require("../assets/images/Projects/todos.png"),
    proPortTemplate: require('../assets/images/Projects/porttemplate.png'),
    proFacial: require("../assets/images/Projects/facialsystem.png"),
    proLoan: require("../assets/images/Projects/loansystem.png"),
    proDominantColor: require("../assets/images/Projects/colordetector.png"),
    proFaq: require("../assets/images/Projects/faq.png"),

    // Certicates
    Certificate1: require("../assets/images/Certifications/cert1.png"),
    Certificate2: require("../assets/images/Certifications/cert2.png"),
    Certificate3: require("../assets/images/Certifications/cert3.png"),
    Certificate4: require("../assets/images/Certifications/cert4.png"),
    Certificate5: require("../assets/images/Certifications/cert5.png"),
    Certificate6: require("../assets/images/Certifications/cert6.png"),
    Certificate7: require("../assets/images/Certifications/cert7.png"),
    Certificate8: require("../assets/images/Certifications/cert8.png"),
    Certificate9: require("../assets/images/Certifications/cert9.png"),
};